# Generated by Django 4.1 on 2023-12-09 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=14, unique=True)),
                ('genero', models.IntegerField()),
                ('peso', models.CharField(max_length=14, unique=True)),
                ('altura', models.CharField(max_length=14, unique=True)),
                ('dataNascimento', models.CharField(max_length=14, unique=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academias.academia')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
    ]
