# Generated by Django 4.1 on 2023-12-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='altura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dataNascimento',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='peso',
            field=models.FloatField(),
        ),
    ]
