# Generated by Django 4.1 on 2023-12-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('horarioFuncionamento', models.TextField(max_length=100, verbose_name='Horario')),
                ('telefone', models.CharField(max_length=14, unique=True, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Academia',
                'verbose_name_plural': 'Academias',
                'ordering': ['id'],
            },
        ),
    ]
