# Generated by Django 4.1 on 2023-12-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='nome',
            field=models.CharField(default=0, max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
