# Generated by Django 4.1 on 2023-12-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='grupo',
            field=models.CharField(max_length=100),
        ),
    ]
