# Generated by Django 4.1 on 2023-12-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricionistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricionista',
            name='email',
            field=models.TextField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='nutricionista',
            name='especialidade',
            field=models.TextField(max_length=100, verbose_name='especialidade'),
        ),
    ]
