# Generated by Django 4.1 on 2023-12-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.IntegerField()),
                ('Maquina', models.IntegerField()),
                ('grupoMuscular', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Exercicio',
                'verbose_name_plural': 'Exercicios',
                'ordering': ['id'],
            },
        ),
    ]
