# Generated by Django 4.1 on 2023-12-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='Maquina',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='grupoMuscular',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
