# Generated by Django 4.1 on 2023-12-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='repeticao',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Repeticao'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='serie',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Serie'),
        ),
    ]
